from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddCoffee(object):
    def setupUi(self, AddCoffee):
        AddCoffee.setObjectName("AddCoffee")
        AddCoffee.resize(424, 422)
        self.sortLine = QtWidgets.QLineEdit(parent=AddCoffee)
        self.sortLine.setGeometry(QtCore.QRect(160, 120, 191, 20))
        self.sortLine.setObjectName("sortLine")
        self.descLine = QtWidgets.QLineEdit(parent=AddCoffee)
        self.descLine.setGeometry(QtCore.QRect(160, 210, 191, 20))
        self.descLine.setObjectName("descLine")
        self.priceLine = QtWidgets.QLineEdit(parent=AddCoffee)
        self.priceLine.setGeometry(QtCore.QRect(160, 240, 191, 20))
        self.priceLine.setObjectName("priceLine")
        self.label = QtWidgets.QLabel(parent=AddCoffee)
        self.label.setGeometry(QtCore.QRect(50, 120, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=AddCoffee)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=AddCoffee)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 111, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=AddCoffee)
        self.label_5.setGeometry(QtCore.QRect(40, 240, 111, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=AddCoffee)
        self.label_6.setGeometry(QtCore.QRect(40, 270, 111, 21))
        self.label_6.setObjectName("label_6")
        self.groundCheck = QtWidgets.QCheckBox(parent=AddCoffee)
        self.groundCheck.setGeometry(QtCore.QRect(70, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groundCheck.setFont(font)
        self.groundCheck.setObjectName("groundCheck")
        self.roastCombo = QtWidgets.QComboBox(parent=AddCoffee)
        self.roastCombo.setGeometry(QtCore.QRect(160, 150, 191, 21))
        self.roastCombo.setObjectName("roastCombo")
        self.roastCombo.addItem("")
        self.roastCombo.addItem("")
        self.roastCombo.addItem("")
        self.sizeCombo = QtWidgets.QComboBox(parent=AddCoffee)
        self.sizeCombo.setGeometry(QtCore.QRect(160, 270, 191, 22))
        self.sizeCombo.setObjectName("sizeCombo")
        self.sizeCombo.addItem("")
        self.sizeCombo.addItem("")
        self.sizeCombo.addItem("")
        self.saveBtn = QtWidgets.QPushButton(parent=AddCoffee)
        self.saveBtn.setGeometry(QtCore.QRect(180, 310, 75, 23))
        self.saveBtn.setObjectName("saveBtn")
        self.errorLine = QtWidgets.QLabel(parent=AddCoffee)
        self.errorLine.setGeometry(QtCore.QRect(50, 370, 311, 20))
        self.errorLine.setText("")
        self.errorLine.setObjectName("errorLine")
        self.idLine = QtWidgets.QLineEdit(parent=AddCoffee)
        self.idLine.setGeometry(QtCore.QRect(140, 50, 161, 21))
        self.idLine.setObjectName("idLine")
        self.label_3 = QtWidgets.QLabel(parent=AddCoffee)
        self.label_3.setGeometry(QtCore.QRect(60, 50, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(parent=AddCoffee)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 121, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=AddCoffee)
        self.label_8.setGeometry(QtCore.QRect(50, 90, 121, 16))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(AddCoffee)
        QtCore.QMetaObject.connectSlotsByName(AddCoffee)

    def retranslateUi(self, AddCoffee):
        _translate = QtCore.QCoreApplication.translate
        AddCoffee.setWindowTitle(_translate("AddCoffee", "Form"))
        self.label.setText(_translate("AddCoffee", "Сорт"))
        self.label_2.setText(_translate("AddCoffee", "Степень обжарки"))
        self.label_4.setText(_translate("AddCoffee", "Описание"))
        self.label_5.setText(_translate("AddCoffee", "Цена"))
        self.label_6.setText(_translate("AddCoffee", "Размер"))
        self.groundCheck.setText(_translate("AddCoffee", "Молотый"))
        self.roastCombo.setItemText(0, _translate("AddCoffee", "Слабообжаренный"))
        self.roastCombo.setItemText(1, _translate("AddCoffee", "Среднеобжаренный"))
        self.roastCombo.setItemText(2, _translate("AddCoffee", "Сильнообжаренный"))
        self.sizeCombo.setItemText(0, _translate("AddCoffee", "Большой пакет"))
        self.sizeCombo.setItemText(1, _translate("AddCoffee", "Средний пакет"))
        self.sizeCombo.setItemText(2, _translate("AddCoffee", "Маленький пакет"))
        self.saveBtn.setText(_translate("AddCoffee", "Сохранить"))
        self.label_3.setText(_translate("AddCoffee", "ID"))
        self.label_7.setText(_translate("AddCoffee", "Обновление по ID"))
        self.label_8.setText(_translate("AddCoffee", "Просто дабавление.."))
